num = set()

num1 = int(input("Enter the no.1 :"))
num.add(num1)
num2 = int(input("Enter the no.2 :"))
num.add(num2)
num3 = int(input("Enter the no.3 :"))
num.add(num3)
num4 = int(input("Enter the no.4 :"))
num.add(num4)
num5 = int(input("Enter the no.5 :"))
num.add(num5)
num6 = int(input("Enter the no.6 :"))
num.add(num6)
num7 = int(input("Enter the no.7 :"))
num.add(num7)
num8 = int(input("Enter the no.8 :"))
num.add(num8)

print(num)